eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  kafka:
    producer:
      bootstrap-servers: 175.197.31.175:9092, 175.197.31.175:9093, 175.197.31.175:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer