eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    producer:
      bootstrap-servers: 172.30.1.77:19092, 172.30.1.77:19093, 172.30.1.77:19094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    producer:
      bootstrap-servers: 175.197.31.175:9092, 175.197.31.175:9093, 175.197.31.175:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer