eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/
spring:
  kafka:
    producer:
      bootstrap-servers: '{cipher}AYAmkm+SAmicGahFJC9b+7dMxPjmVoZMJbiXXAKb2qIE5xSC9FxOKMsIYPp7VGvkBZnxUAdGdBYKdSCHRAq1s2G9yl/O2sDUJNqNblm2Rcikel8SogR04dyVzChzViVMkK4r7ZZy3tmoTpNJM9F5JEtR7xy/3EGnrpXGe135eAsPLOxnxO8u0aCzHA4nxpJQKlb0rHnkElEziMX4yLTyjEv63eF/pR2u4Wfg5RfIp8HJqIoYBRhWO96Jd8NzpHFT+1zuLZH9We+YgVl8cuUzc4BAP/d4kQR7E/drFWoD3u3AzjRrA/i5vQy+bo7Q5kHfG71gXJUw8BPW6qDGrNjjVJ80dFWJ0bGiELxiGvXBH3+zuNbNkgCamhgYWe2+BCq1+bmrMoNXX+Ok8UpTZqrv5V7JiPXo26AkPc/qgvyVaSpeJZ5vblCczSn9/0PKuCFlLfGAJI1dfWW0TBqlC8kEfP03/eN1yntsMP/TFK9sIXkynZF5ZsEJfHSe4yHAFDRoV5GQiAXmc4x930OIO3UDdNeYgaaDyGuHT4ELwULhlPSklkPvqkBGID0oIuhd+E9M1rd809aIzpsFuRNOqUgMDinRlic5RnKEFMiKKPW6MoAwDQ=='
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  zipkin:
    base-url: '{cipher}AYC3G+emTlM2yHfsqFE7HNz1JXEh76co5I4u0tdYfQChv7k2VBJPdmB4kiKn7sUkTUu6BxTeUq9xzXM7BeKbxUAO5X482y0hdeQYOM5/sTZcDjWkl8oinkEG7DbNNKsBpeCQH34QVfD5lhJZIyYyWNu8J1mYyat0fHe8k2eP/vm4MRUjfgUke/STanwYAKvB8tDCNlBlQbvWfBld8fWCwnQsO0kntstaiOSynCi3QyrFVjvMYlqKVYUi/LoeXTTWEWVRaoy79YsHvWGcyewUS+XDdkvjDEDx3pirs7qWzc5T39g031K+MRqNSrQwy1SlHz1zsJzIirj7KaQF6w3QHHf+0QLUNkNPSOgwvUYSrZBpGcWXCjZExETKaE+L1eaV4e+Uv7x0DJXSj5Gg+TdFbke8hZOXzyrDsuXQU7jFLZzkfi8WlggoH9kuPrW10ic9fpouI7PovVLrIjjOOB2t5+CmncodHM9rIVt/svQFFS+DtD+xlqLbqt1mNFIGFOdNMKmF30lro6Bb5PcdLze9A0VqJ191sjp0CZmhrCTlFRNOsLfY99F9Slo+AZOaXjSklfQ='
    enabled: true
  sleuth:
    sampler:
      probability: 1.0