eureka:
  client:
    service-url:
      defaultZone: 
        - 'http://'
        - '{cipher}AYAhzoho2SC2epFeecPmE9kVDUXaHzYEkOGL0rQTdcH0VQVMr8Etpz9NvjN4FwxntQCPdtYnvGvpDf2mL4NLjYSpFNaJMqhq+Rwjffl8krNqwJ1heFY+9skNEWJS8edD0HWWibrErnIId1mBheUjVjBUmfxJZB2rGiqhEOipDnnh8/nYy1NRiMmTDiGXUO2Fl6EgLmoAXUD+5sGTCCFUVxTHPb1JLgBrdgfQ4/rrFFYfdGzWPxK0KIoU75B7Lb1zymov1UAcyE2C6DbvkClfSrwDln+vTMN1ZdTz6l0wyc9yVCtfvSAqzAW/G9L1m1OdHmLDIjZ2kQZ3oEOech+uzkXMxIIeHwAn+SeNR8ONfwA3W2GEa7sGsJKxwcxiDb8To2pIZEWAlpaBcUOSSl6M3qbH6nQEMLPqA71ObYwchuBuvrJmsgiahdE3d3tid4z4ex9BWKiqAPmfWtWxz0JYpENTTOkT/onKklRRDTWzuh4BYb0KAUFGxoKf0HbDzI1wvDdgyiD6kTJrQt2Wk2BKeXxKtFFvUWqPH/Q36VaXLkRBbW3SS6bCSZBbA61fn6OqDoE='
spring:
  kafka:
    producer:
      bootstrap-servers: '{cipher}AYByFEEAG9rITy4LxukgjLAyq+iD6bwDMM7T5KBz1yaDkLMWPJIH/Rp3xWonNEBji0tlFixV24b/jJVF2BuUfeVFSXapB5K88U6A2dMFQhMhkWoEvxL0fd1UQ6qnbpQANLwcWCHgK7cNKlSFahGQT8Z/xX0XwYfnZLAPLLAeCKW7Nklcq8kRy1fmMj7K5TCZVlO9kwKljLI7/ka0mqSEQJiXp5Vje9GCWNVyqoJCz431sCPdWwQbWQPTW/Z3C+QOwADxe403Sya04Qu+QSfOtDm+NDh49/+wcV19iuMpRPYkecH7hzp6MsoHS+LDIv5201bik83fglFJdVL6Sx9VPaYe7uAMTqSnu6Ob5L7H9S8J+fSfyOjhcS5DRAVlrSc/4zth6nW0KsOA2YeZidNA+s0tfS+kHLcHbYtyBz1CFGAWGV+GJapr0cQQOsT9eSjGyH1YFcdPGu2mB7fX5LB8hJwxU+N0aTSPLENGWC/D6cnUzEg6CbfuCp8ahxUD5/QqDC7TxgCC/ODJs0bQWHQEIuX91MTi/iFnGTmkeSfnyhxdlxdnQadN6jg3tbzaoZ5d7t8+FgfZN09Y5MvFqbQeso250dm0bOxcsOYbtYsLtRxUwQ=='
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  zipkin:
    base-url: 
      - 'http://'
      - '{cipher}AYBbDj2yBjWPX/kj5TEdGVa169c/BqEwFJITQH0mvhce+n3kkwTFTeC9oNfFEnnB1zMcYTLj5pvz+2L6dqbTEOexlQsShkhY6CQTkoaQJRSUVP0LBXQ9dJZP2d1GybZIA45I1dtC1Ea4vfeI71PNRnMLDcsCoUrlsu1CMGGOwB5oGsyeAIcpdXlkapdKDec5Go13MKNm/nUZ6jMIxbK3H2OEPqKboL11nZV1qQD7Mqrmz8DF4lYodeeyzH36nRmJRl+auBm+uOpaZyoH0vl7cV8yhnmktEChdU7Mvse4d2mR0s58uRqlYLkv1V/7yNDpk2zVCHaEauPzWXYa23Q75JqF1pMBiVB+ieYHQcE8hE95oxw7abieth9Kkwwu3fOYd3lQdXtzjuUaoCvGCxjGrxLOEkNb7imrDl8+i1WiwNiQFldyEiiKJaDZbyz+0s0ntdTvikCMYicdkzhiFeyE8CqjpdGxak00+q0u6cGK0XVVLLhOngj1VWNDKghBup+cGue2uINiF9TBWRl386qe+3/X3Ha0HEZVJEwgfm1GmvkECsKih7TVTcbpgWNkrFcEayc='
    enabled: true
  sleuth:
    sampler:
      probability: 1.0