eureka:
  client:
    service-url:
      defaultZone: 
        - 'http://'
        - '{cipher}AYAhzoho2SC2epFeecPmE9kVDUXaHzYEkOGL0rQTdcH0VQVMr8Etpz9NvjN4FwxntQCPdtYnvGvpDf2mL4NLjYSpFNaJMqhq+Rwjffl8krNqwJ1heFY+9skNEWJS8edD0HWWibrErnIId1mBheUjVjBUmfxJZB2rGiqhEOipDnnh8/nYy1NRiMmTDiGXUO2Fl6EgLmoAXUD+5sGTCCFUVxTHPb1JLgBrdgfQ4/rrFFYfdGzWPxK0KIoU75B7Lb1zymov1UAcyE2C6DbvkClfSrwDln+vTMN1ZdTz6l0wyc9yVCtfvSAqzAW/G9L1m1OdHmLDIjZ2kQZ3oEOech+uzkXMxIIeHwAn+SeNR8ONfwA3W2GEa7sGsJKxwcxiDb8To2pIZEWAlpaBcUOSSl6M3qbH6nQEMLPqA71ObYwchuBuvrJmsgiahdE3d3tid4z4ex9BWKiqAPmfWtWxz0JYpENTTOkT/onKklRRDTWzuh4BYb0KAUFGxoKf0HbDzI1wvDdgyiD6kTJrQt2Wk2BKeXxKtFFvUWqPH/Q36VaXLkRBbW3SS6bCSZBbA61fn6OqDoE='
spring:
  kafka:
    producer:
      bootstrap-servers: '{cipher}AYAmkm+SAmicGahFJC9b+7dMxPjmVoZMJbiXXAKb2qIE5xSC9FxOKMsIYPp7VGvkBZnxUAdGdBYKdSCHRAq1s2G9yl/O2sDUJNqNblm2Rcikel8SogR04dyVzChzViVMkK4r7ZZy3tmoTpNJM9F5JEtR7xy/3EGnrpXGe135eAsPLOxnxO8u0aCzHA4nxpJQKlb0rHnkElEziMX4yLTyjEv63eF/pR2u4Wfg5RfIp8HJqIoYBRhWO96Jd8NzpHFT+1zuLZH9We+YgVl8cuUzc4BAP/d4kQR7E/drFWoD3u3AzjRrA/i5vQy+bo7Q5kHfG71gXJUw8BPW6qDGrNjjVJ80dFWJ0bGiELxiGvXBH3+zuNbNkgCamhgYWe2+BCq1+bmrMoNXX+Ok8UpTZqrv5V7JiPXo26AkPc/qgvyVaSpeJZ5vblCczSn9/0PKuCFlLfGAJI1dfWW0TBqlC8kEfP03/eN1yntsMP/TFK9sIXkynZF5ZsEJfHSe4yHAFDRoV5GQiAXmc4x930OIO3UDdNeYgaaDyGuHT4ELwULhlPSklkPvqkBGID0oIuhd+E9M1rd809aIzpsFuRNOqUgMDinRlic5RnKEFMiKKPW6MoAwDQ=='
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  zipkin:
    base-url: 
      - 'http://'
      - '{cipher}AYDDwOpkNNtP6gDfS5x/JemDQ3y6MD5Dm8rAEdWKYeY1xb6VifoR34fTQUq4q8xWiH4Iq/XM9QBJP10RVi2GmE63eRPqMTV63x44jiJFgiufvVFwPBo6DnF+mkLXxukotNMyCdko03kj1tfrlzudOVxZDm6BzS4fHuTwXbCJGEsdKEeh/ljWB7ib+iwr3JTvMpGRmTnb/N6UzfGoQCdLZm6hxJvcCaDjgiB+QsQI37jvg7JfXbfXvD77ETV7jZUKOOcqul3GXRWEVsHsjZCx3aOM84PoIgPlzIYaNyvj6wGXPNuEkglHIOWqtax2X8n8oEyaA6aZ++rntTrMy1HFkfh6o6HT6Hd3eaHMDLRmBhZhHZ/Y5/we5i7C3rybXPf3syf2xJ5LW17yQv54UYX8XRxquIUQ5zwHf8/ZocWCNKtJ0y70TA1n0hNG1mqEAQcyshwfS/3LaCe5HnIbLySzWZOH6rLz0X8t1qdd/4/pA+g++U05422a+OufingFzSFtffpGJmuLc+Amvb7BPdNyZp4/Y9UiMSNXLZ4h3PYoiEjj6EhOVD0UwovUI/gLui7Eacc='
    enabled: true
  sleuth:
    sampler:
      probability: 1.0