eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  kafka:
    producer:
      bootstrap-servers: 172.30.1.77:19092, 172.30.1.77:19093, 172.30.1.77:19094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer